### ISSUE TITLE
Rigol DHO800 and DHO900 series

### ISSUE THREAD

**Issue by rgov** [rdpoor/rigol-grab#11]
The command on this scope is `:DISP:DATA? PNG`. The USB product ID on my DHO924S is 0x044C.

I also used https://github.com/rdpoor/rigol-grab/pull/10 since it seemed reasonable, but I don't know if it is necessary.

Reference: [Programming Guide for the DHO800/DHO900 Series](https://www.rigol.eu/Public/Uploads/uploadfile/files/20230823/20230823143925_64e5a99d4dd84.pdf) (PDF)

**Comment by rdpoor** [comment]
I just added support for the DHO924 -- it's a separate script, but works on Windows (haven't had a way to test it on Linux yet).
