### ISSUE TITLE
Simple PowerShell Script

### ISSUE THREAD

**Issue by jwidess** [rdpoor/rigol-grab#13]
I hope this is an appropriate place to post this. I've created a simple **PowerShell** script to aid in running the rigol_grab.py script. All it does is prompt for an IP Address and File name which I found quite useful when needing to do lots of repetitive but unique captures. Below is a short video showing the primary usecase, however it has some error handling built in as well! Let me know what people think about this or if I should create a pull request to add this in. (Used ChatGPT for a lot of the script creation FYI)

1.  Have all dependencies setup as described [here](https://github.com/rdpoor/rigol-grab?tab=readme-ov-file#setup).
2.  Place the script into the folder containing "rigol_grab.py" (Likely \rigol-grab-master)
3.  Launch the script, it will prompt for an IP Address which will be saved to a .txt file for future use.
4.  Enter what the name of the image should be.
5.  Profit $

### .ps1 Script Download: [Grab Rigol Screen V3.zip](https://github.com/rdpoor/rigol-grab/files/15123541/Grab.Rigol.Screen.V3.zip)
(If the script isn't launching properly due to a ExecutionPolicy error then just copying the script into a new file and execute that. PowerShell by default doesn't like you running random scripts from the internet, fair enough lol)

https://github.com/rdpoor/rigol-grab/assets/24278368/c5f495a1-1dcb-4b6d-a6d5-d9b23f2045ec

<details><summary>PS1 Code:</summary>
<p>

```powershell
# Define an array of affirmative responses
$affirmativeResponses = @("Y", "y", "Yes", "yes")

# Define a function to run the script
function RunScript {
    # Get the directory path of the script file
    $scriptDirectory = $PSScriptRoot

    # Define the path to the file to store the IP address
    $ipFilePath = Join-Path -Path $scriptDirectory -ChildPath "rigol_ip_address.txt"

    Write-Host "----------------------------------------------------------------------" -ForegroundColor Blue
    Write-Host "--Grab Rigol Screen V3 Script. Will save outputs to \output folder.--" -ForegroundColor Blue
    Write-Host "--By Justin W. (And ChatGPT)--" -ForegroundColor Blue

    # Check if the IP address file exists
    if (Test-Path $ipFilePath) {
        # If the file exists, read the IP address from it
        $ipAddress = Get-Content $ipFilePath
        Write-Host "Found rigol_ip_address.txt file. IP: $ipAddress"
    } else {
        # If the file doesn't exist, prompt for IP address
        Write-Host "Couldn't find rigol_ip_address.txt file..."
        $ipAddress = Read-Host "Enter IP Address"
        # Save the entered IP address to the file
        $ipAddress | Out-File $ipFilePath
        Write-Host "IP Address saved to rigol_ip_address.txt file."
    }

    # Prompt user for filename
    $filename = Read-Host "Enter filename (without extension)"

    # Append .png extension to the filename
    $filename += ".png"

    # Define the subfolder path
    $subfolderPath = Join-Path -Path $scriptDirectory -ChildPath "output"

    # Ensure the subfolder exists, if not, create it
    if (-not (Test-Path $subfolderPath)) {
        New-Item -Path $subfolderPath -ItemType Directory | Out-Null
    }

    # Activate the Pipenv shell and execute the command
    pipenv run python rigol_grab.py --verbose --filename $filename --port $ipAddress

    # Attempt to move the outputted file to the subfolder
    try {
        Move-Item -Path $filename -Destination $subfolderPath -ErrorAction Stop
        Write-Host "Output file moved successfully."
        # Display the path of the moved file
        Write-Host "Output file path: $($subfolderPath)\$filename"
		Write-Host "Finished! Restarting..." -ForegroundColor Green
    } catch {
        Write-Host "Error occurred while moving the output file: $_" -ForegroundColor Red
        # Prompt the user if they want to change the IP address in the .txt file
        $changeIP = Read-Host "Do you want to change the IP address in the rigol_ip_address.txt file? (yes/no)"
        if ($affirmativeResponses -contains $changeIP) {
            $ipAddress = Read-Host "Enter new IP Address"
            $ipAddress | Out-File $ipFilePath
            Write-Host "IP Address updated in rigol_ip_address.txt file."
            # Restart the script
            RunScript
            return
        }
    }
}

# Run the script in a loop
do {
    RunScript
} while ($true)

Write-Host "Script has ended."
``` 
</p>
</details>

**Comment by rdpoor** [comment]
@jwidess I appreciate your work, but I won't incorporate it into the rigol-grab repository.  This is because rigol-grab is a low-level tool.  For your specific needs, your specific script does the job.  Other users may have entirely different requirements, such as "grab a screenshot once a minute and save with an ISO-formatted timestamp."  MacOS and Linux users don't have PowerShell at all.  Myself, my primary testing is on Windows, but I use a bash shell.  Etc.  I'm sure other people have created custom scripts -- keep yours in a safe place; I trust it will be helpful to your future work!

Best,

- rdp
