### ISSUE TITLE
Could not find Rigol. Check USB?...quitting

### ISSUE THREAD

**Issue by unixneo** [rdpoor/rigol-grab#8]
Hi.  I'm new to RIGOL and have a new DS1054Z, full options.   I have a Mac running the latest version of Catalina connect via USB, have installed rigol-grab (all seems OK) but when I run it, I get:

Could not find Rigol. Check USB?...quitting

Do I need some drivers or other package?

**Comment by unixneo** [comment]
Update:  I assume this python script assume NI-Visa is installed and since Catalina is not yet supported, I cannot use this cool script on macOS Catalina?

**Comment by rdpoor** [comment]
Hi -- I now have both a Mac (running Catalina) and a Windows machine --
I'll double check the current repo on my Mac.  Standby (it might take me a
day to get to it...)

**Comment by unixneo** [comment]
Got this working.... on macOS Catalina... almost.....

All images are corrupted... any clues to solve this
![rigol](https://user-images.githubusercontent.com/12891828/72510579-47355880-387c-11ea-92a2-34360a6a3687.png)

![rigol](https://user-images.githubusercontent.com/12891828/72510652-66cc8100-387c-11ea-9b5e-1fadd6102640.png)

**Comment by unixneo** [comment]
![test1](https://user-images.githubusercontent.com/12891828/72512912-1f93bf80-387f-11ea-820a-7bd035124408.png)

Seems to be working now... :)

See full discussion here, for macOS Catalina users:

https://www.unix.com/programming/283575-python-screen-capture-rigol-1054z-macos-catalina-using-ni-visa.html
